### ISSUE TITLE
Repeating keys, leads to memory error

### ISSUE THREAD

**Issue by vmonaco** [vmonaco/kloak#1]
As reported by @adrelanos:
https://github.com/vmonaco/keystroke-obfuscation/issues/1#issuecomment-270020900

Automatic key repetitions lead to a memory error:

> pthread_create() failed: cannot allocate memory

Typically happens with longer maximum delays.

**Comment by vmonaco** [comment]
So far, I have not been able to reproduce the pthread error above running kloak in a Whonix VirtualBox VM. But I think there might be a way to make kloak single threaded and avoid pthreads altogether: in the main loop, read keyboard events using a non-blocking call and then iterate over every pressed key to check whether to release the event (each keyboard event can be thought of as invoking a timer, and kloak just manages a bunch of these timers). I'm not sure yet if this will work, but it may greatly simplify things.

**Comment by adrelanos** [comment]
Using Whonix 14? (Good!)

Maybe due to the newer Debian version this error no longer reproduces?

Vinnie Monaco:
> I think there might be a way to make kloak single threaded and avoid pthreads altogether

Any disadvantage (such as performance) by that?

**Comment by vmonaco** [comment]
> Using Whonix 14? (Good!)

Yep, just downloaded the latest image. Was this bug reproducible for you? I suspect a synchronization issue, possibly I'm missing a lock somewhere. Not sure if creating a new thread for every event was the right solution anyway since this implicitly makes the scheduler responsible for keeping track of the delays.

> Any disadvantage (such as performance) by that?

The overhead should be negligible, may even be an improvement over the threading solution. There is one possible caveat, which is the loop will need a call to sleep(), or can try to read from the device with a timeout using poll() or select(). The timeout should probably be somewhat small since this is going to quantize the event timings, similar to how the global system clock does. So choosing the right value might take some experimenting.

**Comment by vmonaco** [comment]
Should be fixed, tested on Ubuntu but not yet tested on Whonix. I'll get to testing on Whonix in the next couple days. Solution was to make kloak single threaded. Keyboard events are buffered in a queue for a random amount of time, and the queue is emptied as the current time approaches the scheduled release of each event.

**Comment by vmonaco** [comment]
Fixed in v0.2 by removing pthreads and making kloak single threaded. Tested on latest Whonix and Ubuntu.
