### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by adrelanos** [vmonaco/kloak#25]
Trying to compile kloak in a arm cowbuilder chroot. Failing. But that could just be me not knowing how to package / cross compile for arm.

```
   dh_dwz
        install -d debian/kloak/usr/lib/debug/.dwz/x86_64-linux-gnu
        dwz -q -mdebian/kloak/usr/lib/debug/.dwz/x86_64-linux-gnu/kloak.debug -M/usr/lib/debug/.dwz/x86_64-linux-gnu/kloak.debug -- debian/kloak/usr/sbin/eventcap debian/kloak/usr/sbin/kloak
        x86_64-linux-gnu-objcopy --compress-debug-sections debian/kloak/usr/lib/debug/.dwz/x86_64-linux-gnu/kloak.debug
/usr/bin/x86_64-linux-gnu-objcopy: Unable to recognise the format of the input file `debian/kloak/usr/lib/debug/.dwz/x86_64-linux-gnu/kloak.debug'
dh_dwz: x86_64-linux-gnu-objcopy --compress-debug-sections debian/kloak/usr/lib/debug/.dwz/x86_64-linux-gnu/kloak.debug returned exit code 1
make: *** [debian/rules:13: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

Related:
https://github.com/vmonaco/kloak/issues/24

**Comment by vmonaco** [comment]
Thanks, I haven't tried building for arm, I'll give it a try. But not sure how to package for arm, that I'll have to see if I can figure out. Besides regular usage, this would be useful if, for example, there was a way to use something like a raspberry pi as a HID device that plugs between keyboard and computer.

**Comment by adrelanos** [comment]
I was experiencing these qemu bugs:

* https://github.com/vivier/qemu-m68k/issues/38
* https://bugs.launchpad.net/qemu/+bug/1756519
* https://bugs.launchpad.net/qemu/+bug/1793539

But these tickets are is now saying that these issues where fixed. One could try again in Debian bullseye or or above and/or with higher qemu version.

**Comment by adrelanos** [comment]
Done in https://github.com/Whonix/kloak/pull/1
