### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by adrelanos** [vmonaco/kloak#3]
TODO: Add the necessary files create a Debian package of kloak.

Fun fact: I would like to help with this. Pull request coming very soon.

**Comment by vmonaco** [comment]
Awesome! This is great, I'm looking at the pr now.

**Comment by adrelanos** [comment]
There we go.

https://github.com/vmonaco/kloak/pull/5

**Comment by adrelanos** [comment]
This is done.
