### ISSUE TITLE
compilation warning string_fortified.h:106:10: warning: '__builtin_strncpy' specified bound 

### ISSUE THREAD

**Issue by adrelanos** [vmonaco/kloak#35]
```
gcc src/main.c src/keycodes.c -o kloak -lm -lpthread -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/build/kloak-0.2.29=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wl,-z,now
gcc src/eventcap.c -o eventcap -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/build/kloak-0.2.29=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wl,-z,now
In file included from /usr/include/string.h:495,
                 from src/main.c:2:
In function 'strncpy',
    inlined from 'main' at src/main.c:554:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: '__builtin_strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.c: In function 'main':
src/main.c:554:5: note: length computed here
  554 |     strncpy(_rescue_keys_str, rescue_keys_str, strlen(rescue_keys_str));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by qua3k** [comment]
You shouldn't be using strncpy here. You're wrongly calculating the count argument based on the length of the source when you should be calculating it based on the size of the destination buffer.

**Comment by ArrayBolt3** [comment]
Based on the documentation from `man string_copying`, it appears that `strlcpy` is not ideal. Quoting from the BUGS section of the relevant manpage:

> strlcpy(3) and strlcat(3) need to read the entire src string, even if the destination buffer is small.  This makes them vulnerable to Denial of Service (DoS) attacks if  an  attacker can control the length of the src string.  And if not, they're still unnecessarily slow.

An implementation of an alternative function, `strtcpy`, is provided in the manpage and offered as public-domain. It is specifically mentioned at a `strlcpy` alternative, so I think it's probably the best way to go.

**Comment by adrelanos** [comment]
Sounds good.

**Comment by adrelanos** [comment]
Done in https://github.com/Whonix/kloak/pull/1
