### ISSUE TITLE
merge dev branch into master

### ISSUE THREAD

**Issue by adrelanos** [vmonaco/kloak#60]
https://github.com/vmonaco/kloak/pull/55 was merged into the dev branch.

Now the dev branch is in a weird state. It has https://github.com/vmonaco/kloak/pull/55 but it does not have https://github.com/vmonaco/kloak/pull/53. This can be confusing.

I think a separate dev branch isn't warranted at this stage. I would suggest:

1. merge dev branch into master
2. stop using the dev branch for now

**Comment by vmonaco** [comment]
fixed by #63 and deleted dev branch
