### ISSUE TITLE
Why are we capturing mouse events?

### ISSUE THREAD

**Issue by mattfbacon** [vmonaco/kloak#76]
Kloak runs on my touchpad as well which results in very high CPU usage and noticeably reduces battery life, since the touchpad sends near continuous events while being used, magnitudes more than any keyboard events. But kloak doesn't even run on the mouse, so why?

**Comment by adrelanos** [comment]
* https://github.com/vmonaco/kloak/issues/7
* https://github.com/vmonaco/kloak/pull/38

**Comment by mattfbacon** [comment]
Ah good to know that it serves a purpose.
